runtime:
  device: "cuda"
  dtype: "fp16"         # "fp16" or "fp32"
  seed: 123

data:
  cache_dir: "/workspace/jointdit/data/cache"
  train_split: "train"
  val_split: "val"

loader:
  batch_size: 1
  num_workers: 0
  pin_memory: true

model:
  d_model: 192 # was 256
  heads: 6 # was 8 (keep d_model % heads == 0)
  n_blocks: 2           # Joint blocks (covers Expert 2–3 conceptually)
  ff_mult: 4            # 4 * d_model
  attn_dropout: 0.0
  ff_dropout: 0.0
  rope_video: true
  rope_audio: true

schedule:
  # EDM (video)
  edm_P_mean: -1.2
  edm_P_std: 1.2
  sigma_video_min: 0.01
  sigma_video_max: 1.0

  # Audio "DDPM-like" noise level (Stage-A smoke: scalar sigma)
  sigma_audio_min: 0.01
  sigma_audio_max: 0.5

loss:
  lambda_v: 1.0
  lambda_a: 1.0

optim:
  lr_main: 1.0e-4       # joint blocks / projections
  lr_adaln: 5.0e-5      # AdaLN scale/shift (if present in JointDiT)
  betas: [0.9, 0.999]
  weight_decay: 0.01
  grad_accum: 1
  max_steps: 200
  log_every: 10
  ckpt_every: 100
  amp: true
  grad_clip: 1.0        # set 0 or null to disable

out:
  ckpt_dir: "/workspace/jointdit/checkpoints/day05_stage_a"
  log_dir: "/workspace/jointdit/runs/day05_stage_a"
