name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install black ruff mypy

      # Make imports and mypy happy
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"

      - name: Black (check)
        run: black --check .

      - name: Ruff (lint)
        run: ruff check .

      # Important: only check our packages, not the repo name
      - name: Mypy (type-check)
        run: |
          mypy --namespace-packages --explicit-package-bases \
               models scripts tests
