name: CPU Smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      TORCH_VERSION: "2.3.1"
      VISION_VERSION: "0.18.1"
      AUDIO_VERSION: "2.3.1"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal runtime deps (CPU wheels)
        run: |
          python -m pip install --upgrade pip
          pip install "torch==${TORCH_VERSION}" "torchvision==${VISION_VERSION}" "torchaudio==${AUDIO_VERSION}" --index-url https://download.pytorch.org/whl/cpu
          # Needed for YAML parsing and optional CLIP import path used by infer script
          pip install pyyaml open-clip-torch pillow
          # PyTest
          pip install pytest

      - name: Run quick tests (CPU-only)
        run: |
          pytest -q
