name: CPU Smoke

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps for tests
        run: |
          python -m pip install --upgrade pip
          # tiny deps only; keep this fast
          pip install -q pytest pyyaml
          # CPU-only torch wheel for tests
          pip install -q --index-url https://download.pytorch.org/whl/cpu torch==2.3.*

      - name: Run quick tests (CPU-only)
        env:
          PYTHONPATH: .
        run: |
          pytest -q tests
